In [30]:
import pandas as pd

In [31]:
df = pd.read_csv('sensor_data.csv')

In [32]:
df.head()

,1.242628574371338,1.9297854900360107,9.038387298583984,0.21276496350765228,-0.1635371893644333,-0.17077165842056274,7778990
0,0.967287,1.620924,9.411894,0.038668,0.699005,0.200634,7778990
1,0.828419,1.324034,9.584282,0.037447,0.294612,0.022262,7778990
2,0.349564,1.364737,9.826104,-0.057237,-0.041975,-0.032716,7778990
3,0.306467,1.441353,9.725544,-0.037079,-0.061523,-0.021721,7778990
4,0.332804,1.419805,9.385557,0.124800,0.080198,-0.057762,7778990

In [33]:
df.columns = ['AccX', 'AccY', 'AccZ', 'GyroX', 'GyroY', 'GyroZ', 'Timestamp']

In [34]:
df.head(30)

        AccX      AccY      AccZ     GyroX     GyroY     GyroZ  Timestamp
0   0.967287  1.620924  9.411894  0.038668  0.699005  0.200634    7778990
1   0.828419  1.324034  9.584282  0.037447  0.294612  0.022262    7778990
2   0.349564  1.364737  9.826104 -0.057237 -0.041975 -0.032716    7778990
3   0.306467  1.441353  9.725544 -0.037079 -0.061523 -0.021721    7778990
4   0.332804  1.419805  9.385557  0.124800  0.080198 -0.057762    7778990
5   0.325621  1.403045  9.557945 -0.079229  0.003229 -0.002784    7780598
6   0.392661  1.283331  9.498088  0.007514  0.002007  0.017986    7780598
7   0.330410  1.285726  9.603436 -0.029749 -0.022427 -0.004005    7780598
8   0.330410  1.271360  9.572310  0.014234 -0.005934  0.010044    7780598
9   0.330410  1.218686  9.816526 -0.045020 -0.009599 -0.001562    7780598
10  0.342381  1.256994  9.507666  0.014234  0.016057  0.005768    7780598
11  0.332804  1.206715  9.577099 -0.002870  0.014225 -0.002173    7780598
12  0.158022  1.204320  9.646533 -0.010812  0.001396  0.009434    7780598
13  0.301679  1.189955  9.610620 -0.007147  0.002007  0.008823    7780598
14  0.222668  1.211503  9.627379 -0.030359  0.005672 -0.002173    7780929
15  0.193936  1.156435  9.622590  0.008125 -0.008988  0.002103    7780929
16  0.268159  1.177983  9.653716 -0.001038 -0.004101  0.006990    7782049
17  0.263370  1.170800  9.660899 -0.004703  0.010559 -0.004616    7782049
18  0.447729  1.075029  9.464568  0.170004  0.058818  0.011877    7782049

In [6]:
df.duplicated().sum()

0